// A broad, browsable emoji bank for the page-icon picker, each entry tagged
// with a name + search keywords so the picker's search box can find an emoji
// by word (e.g. "heart", "money", "cat") — not just by pasting the glyph.
// Curated (not the full Unicode set) to stay dependency-free, but wide enough
// to pick a fitting icon. Extend a group's list to add more options.

export interface EmojiEntry {
  char: string;
  name: string;
  /** Lowercased search tokens (name words + extra synonyms). */
  keywords: string[];
}

export interface EmojiGroup {
  label: string;
  emojis: EmojiEntry[];
}

// [char, name, extra space-separated keywords?]
type Raw = [string, string, string?];

function group(label: string, raw: Raw[]): EmojiGroup {
  return {
    label,
    emojis: raw.map(([char, name, extra]) => ({
      char,
      name,
      keywords: Array.from(
        new Set(
          `${name} ${extra ?? ''}`
            .toLowerCase()
            .split(/[\s,]+/)
            .filter(Boolean)
        )
      ),
    })),
  };
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  group('Smileys & people', [
    ['😀', 'grinning face', 'smile happy'],
    ['😄', 'grinning face big eyes', 'smile happy joy'],
    ['😁', 'beaming face', 'grin smile'],
    ['😅', 'grinning sweat', 'nervous laugh phew'],
    ['😂', 'tears of joy', 'laugh lol funny crying'],
    ['🤣', 'rolling on floor laughing', 'rofl lol funny'],
    ['🙂', 'slightly smiling face', 'smile'],
    ['😉', 'winking face', 'wink flirt'],
    ['😊', 'smiling face smiling eyes', 'blush happy'],
    ['😍', 'heart eyes', 'love adore crush'],
    ['🥰', 'smiling face with hearts', 'love adore'],
    ['😘', 'face blowing a kiss', 'kiss love'],
    ['😜', 'winking tongue', 'silly playful'],
    ['🤪', 'zany face', 'crazy goofy silly'],
    ['🤓', 'nerd face', 'geek smart glasses'],
    ['😎', 'smiling face sunglasses', 'cool'],
    ['🥳', 'partying face', 'party celebrate birthday'],
    ['🤩', 'star struck', 'excited amazed wow'],
    ['🤔', 'thinking face', 'hmm consider'],
    ['🤨', 'raised eyebrow', 'skeptic suspicious'],
    ['😐', 'neutral face', 'meh blank'],
    ['😴', 'sleeping face', 'sleep tired zzz'],
    ['😌', 'relieved face', 'calm content'],
    ['😔', 'pensive face', 'sad down'],
    ['😢', 'crying face', 'sad tear'],
    ['😭', 'loudly crying', 'sob sad bawl'],
    ['😤', 'face steam nose', 'frustrated angry'],
    ['😠', 'angry face', 'mad'],
    ['😡', 'pouting face', 'rage angry mad'],
    ['🤯', 'exploding head', 'mind blown shocked'],
    ['😱', 'screaming in fear', 'shocked scared'],
    ['🤗', 'hugging face', 'hug'],
    ['🤫', 'shushing face', 'quiet secret'],
    ['🤥', 'lying face', 'liar pinocchio'],
    ['😶', 'face without mouth', 'silent blank'],
    ['🙄', 'rolling eyes', 'annoyed whatever'],
    ['😇', 'smiling halo', 'angel innocent'],
    ['😋', 'savoring food', 'yum tasty tongue'],
    ['🤒', 'face with thermometer', 'sick ill fever'],
    ['🤕', 'head bandage', 'hurt injured'],
    ['🥵', 'hot face', 'heat sweat'],
    ['🥶', 'cold face', 'freezing frozen'],
    ['👍', 'thumbs up', 'yes like approve good'],
    ['👎', 'thumbs down', 'no dislike bad'],
    ['👏', 'clapping hands', 'applause bravo'],
    ['🙌', 'raising hands', 'celebrate hooray praise'],
    ['🙏', 'folded hands', 'please thanks pray'],
    ['💪', 'flexed biceps', 'strong muscle gym'],
    ['👋', 'waving hand', 'hi hello bye wave'],
    ['🤝', 'handshake', 'deal agreement'],
    ['✌️', 'victory hand', 'peace'],
    ['🤞', 'crossed fingers', 'luck hope'],
    ['👀', 'eyes', 'look watch see'],
    ['🧠', 'brain', 'smart mind think'],
    ['🫶', 'heart hands', 'love'],
    ['👶', 'baby', 'infant child'],
    ['🧒', 'child', 'kid'],
    ['👨', 'man', 'male'],
    ['👩', 'woman', 'female'],
    ['🧑', 'person', 'adult'],
    ['👴', 'old man', 'grandpa elderly'],
    ['👵', 'old woman', 'grandma elderly'],
    ['👨‍👩‍👧‍👦', 'family', 'parents kids'],
    ['👨‍💻', 'man technologist', 'developer coder programmer'],
    ['👩‍💻', 'woman technologist', 'developer coder programmer'],
    ['🕺', 'man dancing', 'dance party'],
    ['💃', 'woman dancing', 'dance party'],
  ]),
  group('Animals & nature', [
    ['🐶', 'dog face', 'puppy pet'],
    ['🐱', 'cat face', 'kitten pet'],
    ['🐭', 'mouse face', 'rodent'],
    ['🐹', 'hamster', 'pet rodent'],
    ['🐰', 'rabbit face', 'bunny'],
    ['🦊', 'fox', ''],
    ['🐻', 'bear', ''],
    ['🐼', 'panda', ''],
    ['🐨', 'koala', ''],
    ['🐯', 'tiger face', ''],
    ['🦁', 'lion', ''],
    ['🐮', 'cow face', ''],
    ['🐷', 'pig face', ''],
    ['🐸', 'frog', ''],
    ['🐵', 'monkey face', ''],
    ['🐔', 'chicken', 'hen'],
    ['🐧', 'penguin', ''],
    ['🐦', 'bird', ''],
    ['🦆', 'duck', ''],
    ['🦉', 'owl', ''],
    ['🐴', 'horse face', ''],
    ['🦄', 'unicorn', 'magic'],
    ['🐝', 'bee', 'honey'],
    ['🦋', 'butterfly', ''],
    ['🐢', 'turtle', 'tortoise'],
    ['🐙', 'octopus', ''],
    ['🐠', 'tropical fish', ''],
    ['🐬', 'dolphin', ''],
    ['🐳', 'whale', ''],
    ['🐊', 'crocodile', 'alligator'],
    ['🐘', 'elephant', ''],
    ['🦒', 'giraffe', ''],
    ['🦓', 'zebra', ''],
    ['🌱', 'seedling', 'plant sprout grow'],
    ['🌲', 'evergreen tree', 'pine forest'],
    ['🌳', 'deciduous tree', 'forest'],
    ['🌴', 'palm tree', 'beach tropical'],
    ['🌵', 'cactus', 'desert'],
    ['🌸', 'cherry blossom', 'flower spring'],
    ['🌷', 'tulip', 'flower'],
    ['🌹', 'rose', 'flower love'],
    ['🌻', 'sunflower', 'flower'],
    ['🍀', 'four leaf clover', 'luck lucky'],
    ['🍁', 'maple leaf', 'autumn fall'],
    ['🍄', 'mushroom', 'fungus'],
    ['🌍', 'globe earth', 'world planet europe africa'],
    ['🌙', 'crescent moon', 'night'],
    ['⭐', 'star', 'favorite'],
    ['🌟', 'glowing star', 'sparkle shine'],
    ['☀️', 'sun', 'sunny weather'],
    ['🌈', 'rainbow', 'pride weather'],
    ['☁️', 'cloud', 'weather cloudy'],
    ['⚡', 'lightning', 'bolt energy power'],
    ['❄️', 'snowflake', 'snow cold winter'],
    ['🔥', 'fire', 'flame hot lit'],
    ['💧', 'droplet', 'water drop'],
    ['🌊', 'wave', 'ocean sea water'],
  ]),
  group('Food & drink', [
    ['🍎', 'red apple', 'fruit'],
    ['🍐', 'pear', 'fruit'],
    ['🍊', 'orange', 'fruit tangerine'],
    ['🍋', 'lemon', 'fruit citrus'],
    ['🍌', 'banana', 'fruit'],
    ['🍉', 'watermelon', 'fruit'],
    ['🍇', 'grapes', 'fruit wine'],
    ['🍓', 'strawberry', 'fruit berry'],
    ['🫐', 'blueberries', 'fruit berry'],
    ['🍒', 'cherries', 'fruit'],
    ['🍑', 'peach', 'fruit'],
    ['🥝', 'kiwi', 'fruit'],
    ['🍅', 'tomato', 'vegetable'],
    ['🥑', 'avocado', 'fruit'],
    ['🥦', 'broccoli', 'vegetable'],
    ['🥕', 'carrot', 'vegetable'],
    ['🌽', 'corn', 'vegetable'],
    ['🥔', 'potato', 'vegetable'],
    ['🍞', 'bread', 'loaf'],
    ['🧀', 'cheese', ''],
    ['🥚', 'egg', ''],
    ['🍔', 'hamburger', 'burger fast food'],
    ['🍟', 'french fries', 'fries chips'],
    ['🍕', 'pizza', ''],
    ['🌭', 'hot dog', ''],
    ['🥪', 'sandwich', ''],
    ['🌮', 'taco', 'mexican'],
    ['🍣', 'sushi', 'japanese'],
    ['🍜', 'ramen', 'noodles soup'],
    ['🍝', 'spaghetti', 'pasta'],
    ['🍲', 'stew', 'pot food'],
    ['🍰', 'shortcake', 'cake dessert'],
    ['🎂', 'birthday cake', 'celebrate'],
    ['🍪', 'cookie', 'biscuit'],
    ['🍫', 'chocolate', 'candy'],
    ['🍩', 'doughnut', 'donut'],
    ['☕', 'coffee', 'tea hot drink cafe'],
    ['🍵', 'tea', 'green tea drink'],
    ['🧃', 'juice box', 'drink'],
    ['🍺', 'beer', 'drink pub'],
    ['🍷', 'wine', 'drink glass'],
    ['🥂', 'clinking glasses', 'cheers celebrate champagne'],
    ['🍾', 'champagne', 'celebrate bottle'],
  ]),
  group('Travel & places', [
    ['🏠', 'house', 'home'],
    ['🏡', 'house with garden', 'home'],
    ['🏢', 'office building', 'work company'],
    ['🏥', 'hospital', 'health'],
    ['🏦', 'bank', 'money finance'],
    ['🏫', 'school', 'education'],
    ['🏨', 'hotel', 'travel'],
    ['⛪', 'church', 'religion'],
    ['🏰', 'castle', ''],
    ['🗼', 'tower', 'tokyo landmark'],
    ['🏝️', 'desert island', 'beach vacation'],
    ['⛰️', 'mountain', 'hike'],
    ['🌋', 'volcano', ''],
    ['🏕️', 'camping', 'tent outdoors'],
    ['✈️', 'airplane', 'flight travel'],
    ['🚀', 'rocket', 'launch space startup'],
    ['🚗', 'car', 'auto vehicle drive'],
    ['🚕', 'taxi', 'cab'],
    ['🚙', 'suv', 'car'],
    ['🚌', 'bus', ''],
    ['🚲', 'bicycle', 'bike cycle'],
    ['🛵', 'scooter', 'moped'],
    ['🚂', 'locomotive', 'train'],
    ['🚆', 'train', 'rail'],
    ['⛵', 'sailboat', 'boat sea'],
    ['🚤', 'speedboat', 'boat'],
    ['🗺️', 'map', 'travel world'],
    ['🧭', 'compass', 'direction navigate'],
    ['📍', 'pin', 'location map place'],
    ['🚦', 'traffic light', 'signal'],
    ['🌉', 'bridge', 'night'],
    ['🎡', 'ferris wheel', 'fair amusement'],
  ]),
  group('Activities & objects', [
    ['⚽', 'soccer ball', 'football sport'],
    ['🏀', 'basketball', 'sport'],
    ['🏈', 'american football', 'sport'],
    ['🎾', 'tennis', 'sport'],
    ['🏐', 'volleyball', 'sport'],
    ['🏓', 'ping pong', 'table tennis sport'],
    ['🎿', 'skis', 'ski snow sport'],
    ['🏂', 'snowboard', 'sport snow'],
    ['🏊', 'swimming', 'swim sport pool'],
    ['🚴', 'cycling', 'bike sport'],
    ['🧗', 'climbing', 'climb sport'],
    ['🎯', 'direct hit', 'target goal darts bullseye'],
    ['🎮', 'video game', 'gaming controller play'],
    ['🎲', 'dice', 'game random'],
    ['🎸', 'guitar', 'music'],
    ['🎹', 'piano', 'music keyboard'],
    ['🎺', 'trumpet', 'music'],
    ['🥁', 'drum', 'music'],
    ['🎵', 'musical note', 'music song'],
    ['🎧', 'headphones', 'music audio listen'],
    ['🎤', 'microphone', 'sing karaoke'],
    ['🎬', 'clapper board', 'movie film'],
    ['📷', 'camera', 'photo picture'],
    ['📹', 'video camera', 'record'],
    ['🎨', 'artist palette', 'art paint design'],
    ['✏️', 'pencil', 'write edit'],
    ['🖊️', 'pen', 'write'],
    ['📚', 'books', 'library read study'],
    ['📖', 'open book', 'read'],
    ['📓', 'notebook', 'notes journal'],
    ['📝', 'memo', 'note write list'],
    ['📌', 'pushpin', 'pin note'],
    ['📎', 'paperclip', 'attach'],
    ['📁', 'folder', 'files directory'],
    ['🗂️', 'card index dividers', 'organize files'],
    ['📅', 'calendar', 'date schedule'],
    ['📆', 'tear off calendar', 'date schedule'],
    ['⏰', 'alarm clock', 'time reminder'],
    ['⏳', 'hourglass', 'time wait'],
    ['🔔', 'bell', 'notification alert'],
    ['🔦', 'flashlight', 'torch light'],
    ['💡', 'light bulb', 'idea'],
    ['🔒', 'locked', 'lock secure private'],
    ['🔑', 'key', 'password access'],
    ['🔧', 'wrench', 'tool fix repair'],
    ['🔨', 'hammer', 'tool build'],
    ['🛠️', 'hammer and wrench', 'tools settings build'],
    ['⚙️', 'gear', 'settings config cog'],
    ['🧰', 'toolbox', 'tools'],
    ['🔬', 'microscope', 'science lab'],
    ['🔭', 'telescope', 'space astronomy'],
    ['💻', 'laptop', 'computer work'],
    ['🖥️', 'desktop computer', 'monitor pc'],
    ['⌨️', 'keyboard', 'type'],
    ['📱', 'mobile phone', 'smartphone cell'],
    ['🖨️', 'printer', 'print'],
    ['💾', 'floppy disk', 'save'],
    ['🔋', 'battery', 'power charge'],
    ['🔌', 'plug', 'power electric'],
  ]),
  group('Symbols & finance', [
    ['❤️', 'red heart', 'love like'],
    ['🧡', 'orange heart', 'love'],
    ['💛', 'yellow heart', 'love'],
    ['💚', 'green heart', 'love'],
    ['💙', 'blue heart', 'love'],
    ['💜', 'purple heart', 'love'],
    ['🖤', 'black heart', 'love'],
    ['🤍', 'white heart', 'love'],
    ['💯', 'hundred points', '100 perfect score'],
    ['✅', 'check mark button', 'done yes complete tick'],
    ['☑️', 'check box', 'done task tick'],
    ['❌', 'cross mark', 'no wrong cancel'],
    ['⭕', 'hollow red circle', 'o correct'],
    ['❓', 'question mark', 'help ask'],
    ['❗', 'exclamation mark', 'important alert'],
    ['⚠️', 'warning', 'caution alert'],
    ['🚫', 'prohibited', 'no forbidden ban'],
    ['♻️', 'recycle', 'reuse green'],
    ['✨', 'sparkles', 'shine new magic clean'],
    ['🎉', 'party popper', 'celebrate congrats'],
    ['🎊', 'confetti ball', 'celebrate party'],
    ['🎁', 'gift', 'present birthday'],
    ['🏆', 'trophy', 'win award champion'],
    ['🥇', 'gold medal', 'first win award'],
    ['🎖️', 'medal', 'award honor'],
    ['💰', 'money bag', 'cash finance rich savings'],
    ['💵', 'dollar banknote', 'money cash usd'],
    ['💳', 'credit card', 'payment money bank'],
    ['🪙', 'coin', 'money cash'],
    ['💎', 'gem stone', 'diamond jewel valuable'],
    ['📈', 'chart increasing', 'growth up profit stocks gain'],
    ['📉', 'chart decreasing', 'loss down decline stocks'],
    ['📊', 'bar chart', 'stats analytics data'],
    ['🧾', 'receipt', 'invoice bill expense'],
    ['🏷️', 'label', 'tag price'],
    ['🧮', 'abacus', 'calculate math count'],
    ['⚖️', 'balance scale', 'justice law weigh legal'],
    ['📢', 'loudspeaker', 'announce megaphone'],
    ['🔗', 'link', 'chain url'],
    ['🧩', 'puzzle piece', 'jigsaw part'],
    ['🚩', 'triangular flag', 'flag mark milestone'],
    ['🏁', 'chequered flag', 'finish race goal'],
    ['💼', 'briefcase', 'work business job'],
    ['🏠', 'home', 'house dashboard'],
    ['⏱️', 'stopwatch', 'timer time'],
    ['🔍', 'magnifying glass', 'search find zoom'],
  ]),
];

/** Flat list of every emoji across all groups. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emojis);

/**
 * Filter emojis by a free-text query, matching against name + keyword tokens
 * (substring match, so "mon" or "one" both find "money"). Multiple terms are
 * AND-ed. Returns everything for an empty query. Results are de-duplicated by
 * glyph (the same glyph can be listed under more than one group).
 */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_EMOJIS;
  const terms = q.split(/\s+/).filter(Boolean);
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const e of ALL_EMOJIS) {
    if (seen.has(e.char)) continue;
    // Every search term must match some keyword (prefix or substring).
    const ok = terms.every((t) => e.keywords.some((k) => k.includes(t)));
    if (ok) {
      seen.add(e.char);
      out.push(e);
    }
  }
  return out;
}
